cutoff: 6.0
seed: 1

data:
  filename: H2O_100.pkl.gz
  test_size: 0.05
  reference_energy: 0.0
  save_dataset: True
  extra_components: {
    ReferenceTensorDataBuilder: {tensor_rank: 1, per_structure: False},
  }


potential:
  preset: TENSOR_1L
  kwargs: {
           compute_energy: False,

           tensor_components: [1],
           }
  scale: False
  shift: False

fit:
  compute_function: ComputeBatchEFTensor
  train_function: ComputeBatchEFTensor
  compute_function_config: {tensor_components: [1],
                            per_structure: False,
                            compute_energy: False,
                            compute_forces: False
  }
  loss: {
    extra_components: {
          WeightedTensorLoss: {weight: 10.0, type: square},
    }
  }

  target_total_updates: 5000

  optimizer: Adam
  opt_params: {learning_rate: 0.05, use_ema: True, ema_momentum: 0.5,
               weight_decay: null, clipnorm: 1.0}
  scheduler: cosine_decay
  scheduler_params: {minimal_learning_rate: 0.0006}

  batch_size: 10
  test_batch_size: 50

  jit_compile: True

  # train_max_n_buckets: auto
  # test_max_n_buckets: auto
  auto_bucket_max_padding: 0.3

  checkpoint_freq: 2
  progressbar: True
  train_shuffle: True
